// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAFbPpbONCnSBPx0Ha3qd2CJGQulQBDvc',
    appId: '1:439267368201:web:6843cc47cae36408f347d8',
    messagingSenderId: '439267368201',
    projectId: 'grocerysearch-417e0',
    authDomain: 'grocerysearch-417e0.firebaseapp.com',
    storageBucket: 'grocerysearch-417e0.appspot.com',
    measurementId: 'G-55XLTCLEPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGar-c-8TvGR8bcHK8AZNGJMKPpfUIyjY',
    appId: '1:439267368201:android:482fceb6d2f1f06df347d8',
    messagingSenderId: '439267368201',
    projectId: 'grocerysearch-417e0',
    storageBucket: 'grocerysearch-417e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByybzyYD34r_Us5zTF52ke4rO8EnBVnqw',
    appId: '1:439267368201:ios:48431ce2119cdb3ff347d8',
    messagingSenderId: '439267368201',
    projectId: 'grocerysearch-417e0',
    storageBucket: 'grocerysearch-417e0.appspot.com',
    iosClientId: '439267368201-bjvdu722d9km5q6pqikiufql3gd3dqah.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFrontEnd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByybzyYD34r_Us5zTF52ke4rO8EnBVnqw',
    appId: '1:439267368201:ios:48431ce2119cdb3ff347d8',
    messagingSenderId: '439267368201',
    projectId: 'grocerysearch-417e0',
    storageBucket: 'grocerysearch-417e0.appspot.com',
    iosClientId: '439267368201-bjvdu722d9km5q6pqikiufql3gd3dqah.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFrontEnd',
  );
}
