name: flutter_front_end
description: A grocery shopper's companion app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  firebase_core: ^2.15.0
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter

  http: '>=1.1.0 <2.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

