FROM ghcr.io/cirruslabs/flutter:stable AS build

WORKDIR /app

COPY pubspec.yaml pubspec.lock* ./
RUN flutter pub get

COPY . .

ARG USE_LOCAL_BACKEND=true
ARG LOCAL_BACKEND_HOST=
ARG LOCAL_BACKEND_PORT=8000

RUN flutter config --enable-web && \
    flutter build web --release \
      --dart-define=USE_LOCAL_BACKEND=${USE_LOCAL_BACKEND} \
      --dart-define=LOCAL_BACKEND_HOST=${LOCAL_BACKEND_HOST} \
      --dart-define=LOCAL_BACKEND_PORT=${LOCAL_BACKEND_PORT}

FROM nginx:1.27-alpine

COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build/web /usr/share/nginx/html

EXPOSE 80
